name: narxoz
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6"
  flutter: ">=3.0.5" 

dependencies:
  auto_route: ^5.0.0
  # async: ^2.9.0
  bloc: ^8.1.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^4.0.6
  dropdown_button2: ^1.7.2
  # dotted_border: ^2.0.0+2
  # easy_localization: ^3.0.1
  equatable: ^2.0.5
  extended_image: ^6.2.1
  # firebase_core: ^1.18.0
  # firebase_messaging: ^11.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  # flutter_blurhash: ^0.7.0
  flutter_html: ^3.0.0-alpha.5 # TODO
  # flutter_local_notifications: ^9.6.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.7
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.3
  fluttertoast: ^8.0.9
  freezed_annotation:
  # geolocator: ^9.0.1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  # grouped_list: ^5.1.2
  # google_maps_flutter: ^2.1.8
  image_picker: ^0.8.5+3
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  liquid_pull_to_refresh: ^3.0.1
  loader_overlay: ^2.0.10
  # logger: ^1.1.0
  lottie: ^1.4.1
  mask_text_input_formatter: ^2.4.0
  meta: ^1.7.0
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  pinput: ^2.2.12
  pretty_dio_logger: ^1.1.1
  provider: ^6.0.3
  pull_to_refresh: ^2.0.0
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  # url_launcher: ^6.1.3
  webview_flutter: ^3.0.4

dev_dependencies:
  auto_route_generator: ^5.0.0
  # bloc_test: ^9.0.3
  build_runner: ^2.2.0
  # dart_code_metrics: ^4.16.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  lint: ^1.10.0
  # mocktail: ^0.3.0



flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/temp/
    # - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
        - asset: assets/fonts/Rubik/Rubik-BlackItalic.ttf
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik/Rubik-BoldItalic.ttf
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
        - asset: assets/fonts/Rubik/Rubik-ExtraBoldItalic.ttf
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
        - asset: assets/fonts/Rubik/Rubik-LightItalic.ttf
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik/Rubik-MediumItalic.ttf
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
        - asset: assets/fonts/Rubik/Rubik-SemiBoldItalic.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Black.ttf
        - asset: assets/fonts/Gilroy/Gilroy-BlackItalic.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Bold.ttf
        - asset: assets/fonts/Gilroy/Gilroy-BoldItalic.ttf
        - asset: assets/fonts/Gilroy/Gilroy-ExtraBold.ttf
        - asset: assets/fonts/Gilroy/Gilroy-ExtraBoldItalic.ttf
        - asset: assets/fonts/Gilroy/Gilroy-RegularItalic.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Light.ttf
        - asset: assets/fonts/Gilroy/Gilroy-LightItalic.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy/Gilroy-MediumItalic.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy/Gilroy-SemiBold.ttf
        - asset: assets/fonts/Gilroy/Gilroy-SemiBoldItalic.ttf
