// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYNRK-MtjHotV97aDn6HzFhHDiEv8IMUA',
    appId: '1:968603263165:web:ced6b5fb06fda09c0257d4',
    messagingSenderId: '968603263165',
    projectId: 'narxozapp-5147c',
    authDomain: 'narxozapp-5147c.firebaseapp.com',
    storageBucket: 'narxozapp-5147c.appspot.com',
    measurementId: 'G-DBW1XGB8QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdhQvicPS5-NW42yP1PTVrD79zrsWi5nA',
    appId: '1:968603263165:android:ffc001d22538469b0257d4',
    messagingSenderId: '968603263165',
    projectId: 'narxozapp-5147c',
    storageBucket: 'narxozapp-5147c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFKPu20xO1wv0IYFSSOVfDziHbtGjuGHM',
    appId: '1:968603263165:ios:9ce660ec1e7b00dc0257d4',
    messagingSenderId: '968603263165',
    projectId: 'narxozapp-5147c',
    storageBucket: 'narxozapp-5147c.appspot.com',
    iosClientId: '968603263165-i6t0dhbqaf3u9a5hpmte278k845bbcid.apps.googleusercontent.com',
    iosBundleId: 'com.qazaqsoft.narxoz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFKPu20xO1wv0IYFSSOVfDziHbtGjuGHM',
    appId: '1:968603263165:ios:9ce660ec1e7b00dc0257d4',
    messagingSenderId: '968603263165',
    projectId: 'narxozapp-5147c',
    storageBucket: 'narxozapp-5147c.appspot.com',
    iosClientId: '968603263165-i6t0dhbqaf3u9a5hpmte278k845bbcid.apps.googleusercontent.com',
    iosBundleId: 'com.qazaqsoft.narxoz',
  );
}
